version: '3.8'

services:
  backend:
    image: tuusuario/sge-backend:latest
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - DB_HOST=sge-postgres-db.postgres.database.azure.com
      - DB_PORT=5432
      - DB_NAME=sistema_planeacion1
      - DB_USER=sge_admin
      - DB_PASSWORD=AzureDB123!
      - DB_SSLMODE=require
      - JWT_SECRET=tu_jwt_secret_production
    restart: unless-stopped

  frontend:
    image: tuusuario/sge-frontend:latest
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_URL=http://localhost:5000/api
    depends_on:
      - backend
    restart: unless-stopped