version: '3.8'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"    # ← Cambiado de 3001 a 5000
    environment:
      - NODE_ENV=production
      - PORT=5000
      - DB_HOST=host.docker.internal  # Para acceder a PostgreSQL local
      - DB_PORT=5432
      - DB_NAME=sistema_planeacion
      - DB_USER=postgres
      - DB_PASSWORD=123
    volumes:
      - ./backend:/app
      - /app/node_modules
    restart: unless-stopped
    networks:
      - app-network

  frontend:
    build:
      context: ./sistema-planeacion-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"    # ← Ahora en puerto 3000 para evitar conflictos
    environment:
      - REACT_APP_API_URL=http://localhost:5000/api
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge