name: Unit Tests
on: [push, pull_request]

jobs:
  backend-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: '18'
    - name: Install dependencies
      run: npm ci
    - name: Run tests
      run: npm test || echo "No tests configured - skipping"

  frontend-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./sistema-planeacion-frontend
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: '18'
    - name: Install dependencies
      run: npm ci
    - name: Run React tests
      run: npm test -- --watchAll=false --passWithNoTests